### ISSUE TITLE
Macro error in draw initiative

### ISSUE THREAD

**Issue by trprado** [Forbidden-Lands-FVTT/fbl-content-modules#1]
In line 77 the entity `token` when calling the method `toggleCombat()` does not has the use of `await` at the start of the sentence. This omission causes an error when you have combat but not have the actor added in the combat.

Current:
```javascript
if (!token.inCombat && game.combat) {
		token.toggleCombat();
	}...
```

Correction:
```javascript
if (!token.inCombat && game.combat) {
		await token.toggleCombat();
	}...
```

Generated Error: ```Uncaught (in promise) TypeError: combatant is undefined```

**Comment by aMediocreDad** [comment]
Hey there!

Thank you for the heads up:)

I'll have it fixed.
