### ISSUE TITLE
Chargen Minstrel 

### ISSUE THREAD

**Issue by lordwey** [Forbidden-Lands-FVTT/fbl-content-modules#15]
When the event "Enlisted" was selected, it is missing the shortbow and the D8 arrows resource. Currently in the cord module it is missing this gear.

**Comment by aMediocreDad** [comment]
Hi, the chargen is not part of the content modules, believe it or not. The feature is part of the core system. I will move this issue over there.

**Comment by lordwey** [comment]
Hi, but it will pull the contents right? As in it should be pulling the contents of the "Events" from the content modules and then populating the gear into the char sheet? No?

**Comment by aMediocreDad** [comment]
Yeah, but that is all the chargen's doing. The core modules contain the information in the book. The chargen is based on a pamphlet that was created long before the books were done. This pamphlet contains outdated gear names, and so if there is a "missing piece of gear", it is the chargen that needs to fixed.

**Comment by lordwey** [comment]
Thanks for the explanations. Was trying to find out where the "Events" was under the core modules but can't locate it.
Will await the team responsible then, thanks!
