### ISSUE TITLE
Add token art to creatures with art in the book

### ISSUE THREAD

**Issue by phenomen** [Forbidden-Lands-FVTT/fbl-content-modules#19]
Many tokens that have art in the books (and images in the module journal assets) use generic "text" tokens. For example all those creatures have an official art (and probably many others):

- bandit
- bear
- goblin
- donkey
- minstrel
- raven
- rider
- saurian
- sorcerer
- thief
- villager
- whiner
- wolf

**Comment by r-valyar** [comment]
Any change to get this in the module?

**Comment by aMediocreDad** [comment]
I have added those I found. I did not add Donkey, or Bear. Donkey because it was too low resolution and Bear because I could not find it. If there are any other tokens that could use illustrations and not text then please open an issue with name of actor and book + page I can find the illustration.
