### ISSUE TITLE
Peddler Talents differ from the Errata/5th Printing

### ISSUE THREAD

**Issue by coredump** [Forbidden-Lands-FVTT/fbl-content-modules#20]
Hello, on the Errata/5th Printing of the Players Book we have 
![image](https://user-images.githubusercontent.com/52981/212489820-b3eaf511-f46f-437d-b07c-42e8902f7e0c.png)

But on the Foundry module it still:
![image](https://user-images.githubusercontent.com/52981/212489892-33eaff9b-0821-4956-9fd4-696994c6689f.png)

And the mechanics are also not matching.

**Comment by aMediocreDad** [comment]
Fixed
