### ISSUE TITLE
Double buildings/hirelings/items when adding them to stronghold sheet

### ISSUE THREAD

**Issue by Ezekiel-2703** [Forbidden-Lands-FVTT/fbl-content-modules#21]
Hi.

I wanted to report an issue in the FL module of Foundry VTT. When creating a stronghold from the actor tab, adding any building, hireling or items to the stronghold sheet will cause two items to be created. This in itself would not be a big issue but each double item cannot be removed: the error "undefined id [numbers here ]is not in the set of invalid ids" is reported when you try to remove the double buildings/hirelings/items in the stronhold.

Is there a workaround for this while this is being worked at? Currently the stronghold functionality is now unuseable in Foundry VTT for FL.

Kind regards,

Ezekiel

![bug Stronghold](https://github.com/aMediocreDad/fbl-content-modules/assets/113899330/ab95b88c-a51a-4be1-af4e-65409ec6b129)

![bug Stronghold2](https://github.com/aMediocreDad/fbl-content-modules/assets/113899330/36a071ed-68f7-408d-8420-392ab9693700)

**Comment by aMediocreDad** [comment]
Moved
