### ISSUE TITLE
Weatherstone Location Entries

### ISSUE THREAD

**Issue by shanejensen** [Forbidden-Lands-FVTT/fbl-content-modules#22]
Noticed that the Numbers for locations in Weatherstone, are wrong in the Journal, they don't match the PDF.   I ran this last weekend, and ended up getting confused on which location was which.  Especially ones with similar names.

Seems to be the same for other locations in the Core Book, perhaps in other books too.  Ideally they have matching numbers as the PDF, or are at least in the same order.

**Comment by aMediocreDad** [comment]
The idea is that you should not need to play with the pdf. And just reference the locations using Foundry. So it was not made with that in mind. I can move the ones in the core book, but I will not be doing so for all of them as that is a big undertaking.
