### ISSUE TITLE
Error when trying to import Ravens Purge or Core modules

### ISSUE THREAD

**Issue by narukaioh** [Forbidden-Lands-FVTT/fbl-content-modules#23]
About error:
Error when trying to import Ravens Purge and Core modules in version 11 build 311 of the foundry

I created a new world, configured it for Forbidden Lands and I'm only using the two Core and Ravens Purge modules

OS: Ubuntu 20..04.4 LTS
Client: Chrome
Foundry version: 11 build 311

Logs:
![Screenshot from 2023-10-09 20-39-43](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/assets/359991/f17b566d-ed2d-4eaa-9b23-a589cc85726e)

**Comment by aMediocreDad** [comment]
This is an issue with Tokenizer, not the modules.
