### ISSUE TITLE
Tables for Adventure Site generation are missing in the core module table library

### ISSUE THREAD

**Issue by r-valyar** [Forbidden-Lands-FVTT/fbl-content-modules#24]
Tables from chapter 8 - Adventure Site generation are missing in the core module table library.

Using the D66 macro available from the module is not an option, as the macro does not take into account the roll privacy settings and are always public. 

1. Create FL world
2. Load Core Module
3. Adventure site generation tables from chapter 8 of Gamemaster's Guide are missing in the tables library

Foundry: v11.315
System: v11.4.1
Core Module: v6.0

**Comment by aMediocreDad** [comment]
Adventure sites will from V12 on be generated using the "Create Adventure Site"-button:

<img width="251" alt="Screenshot 2024-07-12 at 10 40 08" src="https://github.com/user-attachments/assets/785b541a-63c3-4882-b951-f2e6172c3857">
