### ISSUE TITLE
[Bug] Problem in Solo > General Encounters roll table (Book of Beasts module)

### ISSUE THREAD

**Issue by 9littlebees** [Forbidden-Lands-FVTT/fbl-content-modules#26]
The General Encounters roll table list gives Adventure Sites a 3 / 14 chance of occuring, but in the tables in the book it is only a 1/14 (BoB p169). Having adventure sites spawn this seldom was a conscious design decision for the solo rules and really needs to be reflected in the roll table. Ideally I think there should be a second roll table for Adventure Sites (using a D6 as in the book) which the General Table then draws on.

**Comment by aMediocreDad** [comment]
I am not sure, I am understanding this correctly. The "General Encounters" table in the BoB module only has an Adventure site at 1/52 chance.
<img width="571" alt="Screenshot 2024-07-12 at 10 47 52" src="https://github.com/user-attachments/assets/4feb8ccc-8212-4c11-b0fb-f643fd41c245">

The Journeying rules table seems to be outdated. When I made this module I only had access to the beta of the books. It seems the final rules changes you made were not implemented in the version I had to work with. I'll see about updating where I can find there are differences.
