### ISSUE TITLE
Absolute path for logo in Raven purge module

### ISSUE THREAD

**Issue by fgloppe** [Forbidden-Lands-FVTT/fbl-content-modules#4]
In file 

The path for the logo in fbl-rp.css is absolute. It should be relative as the others (it is useful for installation with a route prefix):

Here is the fix that works for me:
```
#logo {
        content: url("../assets/fbl-logo.svg");
        width: 170px;
}
```

**Comment by aMediocreDad** [comment]
Hi! Thank you for mentioning this. It has been on my radar but I haven't gotten around to sorting it out.

There's a problem on Firefox where the logo won't display at all and so today I wrote a completely different fix that solves that issue as well. 

I'll close this for now, as a future release is not in the cards yet (want to get some other stuff implemented in the system first so I can beat two birds with one stone).

I'll ping you by posting again here once the release is out (maybe sometime end of summer).
