### ISSUE TITLE
Artefact missing in Forbidden Lands - core game: Rustbite

### ISSUE THREAD

**Issue by fgloppe** [Forbidden-Lands-FVTT/fbl-content-modules#5]
The Algarod’s sword Rustbite from Weathersone is not available in the artefact items. It can be found in the Algarod's tower
It's not really a big deal since we can add it ourselves but since it is the first artefact I gave to the players before playing with foundry, I noticed that it was missing when I created the character sheets :)

**Comment by aMediocreDad** [comment]
It's not missing per se. King Algarod has it. Since it wasn't mentioned under the Artifacts chapter it is not with the other Artifacts. There are a few others like that scattered around in the books.

**Comment by fgloppe** [comment]
OK I get it :)
