### ISSUE TITLE
Missing some text for Ravenhole

### ISSUE THREAD

**Issue by JhaelenTerear** [Forbidden-Lands-FVTT/fbl-content-modules#9]
Hi,

The journal items for Ravenhole - The Dance Floor, Ravenhole - Iron Cages and Ravenhole - Fighting Ring and Latrine are present but empty.

**Comment by aMediocreDad** [comment]
Thank you for reporting! I'll look into it asap and hopefully have a patch out with a few fixes within a week or two of the latest system update coming out.

**Comment by JhaelenTerear** [comment]
Perfect, thank you very much ! My group is far for Ravenhole and I have the legit book in PDF so I'm not alone in the woods ;-).

**Comment by JhaelenTerear** [comment]
Again for Ravenhole, I saw that the location "The Carriageway" has the text of "Fighting Ring and Latrine". I think this adventure site has been a little messed up by the Ogre's party (which I'm going to put in music with The Hu in my campaign !).

**Comment by aMediocreDad** [comment]
The missing content has been found and reinserted. Will be fixed when modules are updated.
